name = "webuy-stock-alerts"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-12-17"


[triggers]
crons = ["* * * * *"]
